In [2]:
%reload_kedro

2021-02-25 00:43:55,764 - root - INFO - ** Kedro project coursing-ml
2021-02-25 00:43:55,767 - root - INFO - Defined global variable `context` and `catalog`

In [3]:
df = catalog.load("coursera_raw")
df

2021-02-25 00:43:55,776 - kedro.io.data_catalog - INFO - Loading data from `coursera_raw` (CSVDataSet)...

,Unnamed: 0,category,description,difficulty,duration,duration_week,enrolled,id_course,institution,instructor,...,views,rating,section,skills,title,url,subcategory,hours_months,hours_week,total_hours
0,0,Data Science,"Obtén las , para un puesto de analista de dato...",Beginner Level,Approximately 10 months to complete,Suggested pace of 3 hours/week,NaN,certificado-profesional-analista-de-datos-de-ibm,IBM,Taught by top companies and universities,...,9411.0,4.4,professional-certificates,"Microsoft Excel,Python Programming,Data Analys...",Analista de Datos de IBM Professional Certificate,https://www.coursera.org/professional-certific...,Data Analysis,10.0,3.0,120.0
1,1,Information Technology,"In this 5-course certificate program, you’ll p...",Professional Certificate from Google,Approximately 6 months to complete,Suggested pace of 10 hours/week,539663.0,google-it-support,Google,Google,...,1109.0,4.8,professional-certificates,"Debugging,Encryption Algorithms and Techniques...",Google IT Support Professional Certificate,https://www.coursera.org/professional-certific...,Support and Operations,6.0,10.0,240.0
2,2,Information Technology,"This new beginner-level, six-course certificat...",Beginner Level,Approximately 8 months to complete,Suggested pace of 5 hours/week,207353.0,google-it-automation,Google,Google,...,632521.0,4.7,professional-certificates,"Using Version Control,Troubleshooting & Debugg...",Google IT Automation with Python Professional ...,https://www.coursera.org/professional-certific...,Support and Operations,8.0,5.0,160.0
3,3,Computer Science,Специализация проведет слушателя через все эта...,Beginner Level,Approximately 6 months to complete,Suggested pace of 2 hours/week,NaN,proyektirovaniye-sayta,Saint Petersburg State University,Anna Zyrianova,...,NaN,3.9,specializations,"Design,Internet,Wordpress,Hypertext Preprocess...",Проектирование сайта Specialization,https://www.coursera.org/specializations/proye...,Software Development,6.0,2.0,48.0
4,4,Health,Este curso explica un conjunto de conceptos y ...,Beginner Level,Approx. 9 hours to complete,NaN,40461.0,agricultura-urbana,Universidad Nacional Autónoma de México,Beverly Hernández Castro,...,45074.0,4.7,learn,NaN,Agricultura urbana y periurbana,https://www.coursera.org/learn/agricultura-urbana,Nutrition,9.0,0.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6589,6589,Business,This course is the third course in the five-co...,Intermediate Level,Approx. 20 hours to complete,NaN,6894.0,accounting-analysis-2-liabilities,University of Illinois at Urbana-Champaign,Adel Ibrahim,...,75746.0,4.7,learn,NaN,Accounting Analysis II: Measurement and Disclo...,https://www.coursera.org/learn/accounting-anal...,Business Essentials,20.0,0.0,20.0
6590,6590,Business,Accounting Analytics explores how financial st...,NaN,Approx. 10 hours to complete,NaN,88453.0,accounting-analytics,University of Pennsylvania,This Course Plus the Full Specialization,...,39080.0,4.5,learn,"Accounting,Analytics,Earnings Management,Finance",Accounting Analytics,https://www.coursera.org/learn/accounting-anal...,Finance,10.0,0.0,10.0
6591,6591,Data Science,This course focuses on developing Python skill...,Intermediate Level,Approx. 32 hours to complete,NaN,6824.0,accounting-data-analytics-python,University of Illinois at Urbana-Champaign,This Course Plus the Full Specialization,...,30674.0,4.0,learn,"Python Programming,Data Visualization (DataViz...",Accounting Data Analytics with Python,https://www.coursera.org/learn/accounting-data...,Data Analysis,32.0,0.0,32.0
6592,6592,Business,This course presents an introduction to the ba...,Beginner Level,Approx. 8 hours to complete,NaN,16837.0,accounting-finance,Indian School of Business,Ramabhadran Thirumalai,...,13487.0,4.6,learn,NaN,Accounting and Finance for IT professionals,https://www.coursera.org/learn/accounting-finance,Finance,8.0,0.0,8.0
6593,6593,Business,Accounting information is the lifeblood of the...,Beginner Level,Approx. 16 hours to complete,NaN,11984.0,business-accounting,University of Illinois at Urbana-Champaign,"Gary Hecht, Ph.D.",...,17791.0,4.0,learn,NaN,Accounting for Business Decision Making: Measu...,https://www.coursera.org/learn/business-accoun...,Business Essentials,16.0,0.0,16.0

In [4]:
### Borrar las que no sirven
del df['Unnamed: 0']
del df['hours_months']
del df['hours_week']
del df['duration']
del df['url']
del df['id_course']
del df['duration_week']
del df['skills']
df

c:\users\enrmeao\pycharmprojects\coursing\venv\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,category,description,difficulty,enrolled,institution,instructor,language,n_ratings,views,rating,section,title,subcategory,total_hours
0,Data Science,"Obtén las , para un puesto de analista de dato...",Beginner Level,NaN,IBM,Taught by top companies and universities,Spanish,26.0,9411.0,4.4,professional-certificates,Analista de Datos de IBM Professional Certificate,Data Analysis,120.0
1,Information Technology,"In this 5-course certificate program, you’ll p...",Professional Certificate from Google,539663.0,Google,Google,English,1.0,1109.0,4.8,professional-certificates,Google IT Support Professional Certificate,Support and Operations,240.0
2,Information Technology,"This new beginner-level, six-course certificat...",Beginner Level,207353.0,Google,Google,English,24721.0,632521.0,4.7,professional-certificates,Google IT Automation with Python Professional ...,Support and Operations,160.0
3,Computer Science,Специализация проведет слушателя через все эта...,Beginner Level,NaN,Saint Petersburg State University,Anna Zyrianova,Russian,11.0,NaN,3.9,specializations,Проектирование сайта Specialization,Software Development,48.0
4,Health,Este curso explica un conjunto de conceptos y ...,Beginner Level,40461.0,Universidad Nacional Autónoma de México,Beverly Hernández Castro,Spanish,816.0,45074.0,4.7,learn,Agricultura urbana y periurbana,Nutrition,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6589,Business,This course is the third course in the five-co...,Intermediate Level,6894.0,University of Illinois at Urbana-Champaign,Adel Ibrahim,English,75.0,75746.0,4.7,learn,Accounting Analysis II: Measurement and Disclo...,Business Essentials,20.0
6590,Business,Accounting Analytics explores how financial st...,NaN,88453.0,University of Pennsylvania,This Course Plus the Full Specialization,English,2679.0,39080.0,4.5,learn,Accounting Analytics,Finance,10.0
6591,Data Science,This course focuses on developing Python skill...,Intermediate Level,6824.0,University of Illinois at Urbana-Champaign,This Course Plus the Full Specialization,English,34.0,30674.0,4.0,learn,Accounting Data Analytics with Python,Data Analysis,32.0
6592,Business,This course presents an introduction to the ba...,Beginner Level,16837.0,Indian School of Business,Ramabhadran Thirumalai,English,422.0,13487.0,4.6,learn,Accounting and Finance for IT professionals,Finance,8.0
6593,Business,Accounting information is the lifeblood of the...,Beginner Level,11984.0,University of Illinois at Urbana-Champaign,"Gary Hecht, Ph.D.",English,126.0,17791.0,4.0,learn,Accounting for Business Decision Making: Measu...,Business Essentials,16.0

In [5]:
import pandas as pd
from pandas_profiling import ProfileReport

#EDA using pandas-profiling
profile = ProfileReport(df, explorative=True)

#Saving results to a HTML file
profile.to_file("output_preprocessing.html")

c:\users\enrmeao\pycharmprojects\coursing\venv\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Summarize dataset:   0%|          | 0/27 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

## Missing Data Imputation

In [18]:
df.isnull().sum()

category          0
description       0
difficulty     3208
enrolled        925
institution    1672
instructor     2489
language       1183
n_ratings         0
views          1636
rating         1075
section           0
title             0
subcategory       0
total_hours       0
dtype: int64

### Category & subcategory: Borrar filas

In [7]:
from feature_engine.imputation import DropMissingData

In [8]:
# set up the imputer
missingdata_imputer = DropMissingData(variables=['category', 'subcategory'])

# fit the imputer
missingdata_imputer.fit(df)
df = missingdata_imputer.transform(df)

In [9]:
df[df["category"].isnull()]

Empty DataFrame
Columns: [category, description, difficulty, enrolled, institution, instructor, language, n_ratings, views, rating, section, title, subcategory, total_hours]
Index: []

### Description: String vacío

In [13]:
from feature_engine.imputation import CategoricalImputer

In [17]:
df[df["description"].isnull()]

Empty DataFrame
Columns: [category, description, difficulty, enrolled, institution, instructor, language, n_ratings, views, rating, section, title, subcategory, total_hours]
Index: []

In [11]:
df.iloc[53]

category                                      Business
description                                        NaN
difficulty                                         NaN
enrolled                                           NaN
institution                                        NaN
instructor                                         NaN
language                                           NaN
n_ratings                                          1.0
views                                              NaN
rating                                             NaN
section                                       projects
title          Análisis de Variación con Google Sheets
subcategory                          Business Strategy
total_hours                                        0.0
Name: 53, dtype: object

In [15]:

# set up the imputer
imputer = CategoricalImputer(variables=['description'], fill_value='')

# fit the imputer
imputer.fit(df)

# transform the data
df = imputer.transform(df)

In [16]:
df

,category,description,difficulty,enrolled,institution,instructor,language,n_ratings,views,rating,section,title,subcategory,total_hours
0,Data Science,"Obtén las , para un puesto de analista de dato...",Beginner Level,NaN,IBM,Taught by top companies and universities,Spanish,26.0,9411.0,4.4,professional-certificates,Analista de Datos de IBM Professional Certificate,Data Analysis,120.0
1,Information Technology,"In this 5-course certificate program, you’ll p...",Professional Certificate from Google,539663.0,Google,Google,English,1.0,1109.0,4.8,professional-certificates,Google IT Support Professional Certificate,Support and Operations,240.0
2,Information Technology,"This new beginner-level, six-course certificat...",Beginner Level,207353.0,Google,Google,English,24721.0,632521.0,4.7,professional-certificates,Google IT Automation with Python Professional ...,Support and Operations,160.0
3,Computer Science,Специализация проведет слушателя через все эта...,Beginner Level,NaN,Saint Petersburg State University,Anna Zyrianova,Russian,11.0,NaN,3.9,specializations,Проектирование сайта Specialization,Software Development,48.0
4,Health,Este curso explica un conjunto de conceptos y ...,Beginner Level,40461.0,Universidad Nacional Autónoma de México,Beverly Hernández Castro,Spanish,816.0,45074.0,4.7,learn,Agricultura urbana y periurbana,Nutrition,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6589,Business,This course is the third course in the five-co...,Intermediate Level,6894.0,University of Illinois at Urbana-Champaign,Adel Ibrahim,English,75.0,75746.0,4.7,learn,Accounting Analysis II: Measurement and Disclo...,Business Essentials,20.0
6590,Business,Accounting Analytics explores how financial st...,NaN,88453.0,University of Pennsylvania,This Course Plus the Full Specialization,English,2679.0,39080.0,4.5,learn,Accounting Analytics,Finance,10.0
6591,Data Science,This course focuses on developing Python skill...,Intermediate Level,6824.0,University of Illinois at Urbana-Champaign,This Course Plus the Full Specialization,English,34.0,30674.0,4.0,learn,Accounting Data Analytics with Python,Data Analysis,32.0
6592,Business,This course presents an introduction to the ba...,Beginner Level,16837.0,Indian School of Business,Ramabhadran Thirumalai,English,422.0,13487.0,4.6,learn,Accounting and Finance for IT professionals,Finance,8.0
6593,Business,Accounting information is the lifeblood of the...,Beginner Level,11984.0,University of Illinois at Urbana-Champaign,"Gary Hecht, Ph.D.",English,126.0,17791.0,4.0,learn,Accounting for Business Decision Making: Measu...,Business Essentials,16.0

### Difficulty

In [22]:
df[df["difficulty"].isnull()]

,category,description,difficulty,enrolled,institution,instructor,language,n_ratings,views,rating,section,title,subcategory,total_hours
23,Business,Advanced Competitive Strategy will introduce n...,NaN,59504.0,Ludwig-Maximilians-Universität München (LMU),Tobias Kretschmer,English,803.0,12591.0,4.7,learn,Advanced Competitive Strategy,Business Strategy,12.0
24,Computer Science,"Trotz aller guten Absichten, harter Arbeit und...",NaN,0.0,University of Virginia,Alex Cowan,German,1.0,NaN,NaN,learn,Agiles Arbeiten trifft auf Design Thinking,Design and Product,10.0
36,Business,"This course focuses on technical, mobile and s...",NaN,31626.0,"University of California, Davis",Dave Lloyd,English,444.0,27523.0,4.5,learn,Advanced Search Engine Optimization Strategies,Marketing,25.0
37,Computer Science,"Несмотря на хорошие намерения, упорный труд и ...",NaN,0.0,University of Virginia,Alex Cowan,Russian,1.0,NaN,NaN,learn,Agile и дизайн-мышление,Design and Product,10.0
42,Computer Science,,NaN,2226.0,NaN,NaN,NaN,1.0,NaN,4.5,projects,Analyzing Video with OpenCV and NumPy,Software Development,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6580,Computer Science,,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,projects,Access SQLite in an Android Studio Project,Mobile and Web Development,0.0
6581,Computer Science,,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,projects,Access WebView in an Android Studio Project,Mobile and Web Development,0.0
6583,Business,The first course in the Sales Operations/Manag...,NaN,10411.0,West Virginia University,This Course Plus the Full Specialization,English,170.0,21003.0,4.5,learn,Account Management & Sales Force Design,Leadership and Management,15.0
6584,Computer Science,,NaN,NaN,NaN,NaN,NaN,1.0,NaN,4.9,projects,Accessible Landing Page Solutions in XD,Design and Product,0.0
6590,Business,Accounting Analytics explores how financial st...,NaN,88453.0,University of Pennsylvania,This Course Plus the Full Specialization,English,2679.0,39080.0,4.5,learn,Accounting Analytics,Finance,10.0