# Filter method

With feature selection, we can have:
* simplification of models to make them easier to interpret
* shorter training times and lesser computational cost
* lesser cost in data collection
* avoid the curse of dimensionality
* enhanced generalization by reducing overfitting

In [1]:
import pandas as pd
import numpy as np

c:\users\enrmeao\pycharmprojects\coursing\venv\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [2]:
df = pd.read_csv('output_feature_engenieering.csv')
del df['Unnamed: 0']
df

,collaboration,description,difficulty,duration,free,id_course,n_reviews,rating,skills,title,url,time_range,difficulty_Career Advancement,difficulty_School of Artificial Intelligence,difficulty_School of Autonomous Systems,difficulty_School of Business,difficulty_School of Cloud Computing,difficulty_School of Data Science,difficulty_School of Programming & Development
0,Insight,"Learn to design data models, build data wareho...",2.0,2.156885,0,nd027,0.967871,0.574993,"Data Modeling, Data Pipelines, Data Lakes, Spa...",Become a Data Engineer,https://www.udacity.com/course/data-engineer-n...,months,0,0,0,0,0,1,0
1,"Google, Hootsuite, HubSpot, MailChimp, Moz, Fa...","Learn to create marketing content, use social ...",1.0,0.789128,0,nd018,0.983936,0.788154,"Digital Marketing, Social Media Marketing, Fac...",Become a Digital Marketer,https://www.udacity.com/course/digital-marketi...,months,0,0,0,1,0,0,0
2,None,Youâ€™ll learn how to create a digital user expe...,1.0,0.789128,0,nd578,0.935743,0.809220,"User Research, User Experience, Prototyping, I...",Become a UX Designer,https://www.udacity.com/course/ux-designer-nan...,months,0,0,0,1,0,0,0
3,"AWS, Facebook Artificial Intelligence","Become an expert in neural networks, and learn...",2.0,1.473007,0,nd101,0.991968,0.732811,"Deep Learning, Neural Networks, Jupyter Notebo...",Deep Learning,https://www.udacity.com/course/deep-learning-n...,months,0,1,0,0,0,0,0
4,None,The goal of the Full Stack Web Developer Nanod...,2.0,1.473007,0,nd0044,0.915663,0.558763,"Python, JavaScript, PostgreSQL, Flask, Docker,...",Full Stack Web Developer,https://www.udacity.com/course/full-stack-web-...,months,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,"Kaggle, AWS",Learn foundational machine learning algorithms...,2.0,0.789128,0,nd229,0.879518,0.854073,"Introduction to Machine Learning, Supervised L...",Intro to Machine Learning with PyTorch,https://www.udacity.com/course/intro-to-machin...,months,0,1,0,0,0,0,0
246,None,Build sustainable profit streams from products...,2.0,-0.578630,0,nd037-3,0.000000,NaN,"Product Management, Monetization Models, Prici...",Monetization Strategy Course,https://www.udacity.com/course/monetization-st...,month,0,0,0,1,0,0,0
247,WorldQuant,"Learn the basics of quantitative analysis, inc...",2.0,2.840764,0,nd880,0.911647,0.613715,"Momentum Trading Strategy, Smart Beta, Alpha F...",Artificial Intelligence for Trading,https://www.udacity.com/course/ai-for-trading-...,months,0,1,0,0,0,0,0
248,None,Learn the essential foundations of AI: the pro...,1.0,0.789128,0,nd089,0.963855,0.677144,"Python, NumPy, Pandas, Matplotlib, PyTorch",AI Programming with Python,https://www.udacity.com/course/ai-programming-...,months,0,1,0,0,0,0,0
249,None,Perform analysis on data stored in relational ...,1.0,0.105249,0,nd072,0.823293,0.444812,"SQL, PostgreSQL, JOINs, Subqueries, Window Fun...",Learn SQL,https://www.udacity.com/course/learn-sql--nd072,months,0,0,0,0,0,1,0

# Borrar columnas innecesarias

In [3]:
del df['collaboration']
del df['id_course']
del df['description']
del df['url']
del df['title']
del df['skills']
del df['time_range']

c:\users\enrmeao\pycharmprojects\coursing\venv\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [4]:
df

,difficulty,duration,free,n_reviews,rating,difficulty_Career Advancement,difficulty_School of Artificial Intelligence,difficulty_School of Autonomous Systems,difficulty_School of Business,difficulty_School of Cloud Computing,difficulty_School of Data Science,difficulty_School of Programming & Development
0,2.0,2.156885,0,0.967871,0.574993,0,0,0,0,0,1,0
1,1.0,0.789128,0,0.983936,0.788154,0,0,0,1,0,0,0
2,1.0,0.789128,0,0.935743,0.809220,0,0,0,1,0,0,0
3,2.0,1.473007,0,0.991968,0.732811,0,1,0,0,0,0,0
4,2.0,1.473007,0,0.915663,0.558763,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
245,2.0,0.789128,0,0.879518,0.854073,0,1,0,0,0,0,0
246,2.0,-0.578630,0,0.000000,NaN,0,0,0,1,0,0,0
247,2.0,2.840764,0,0.911647,0.613715,0,1,0,0,0,0,0
248,1.0,0.789128,0,0.963855,0.677144,0,1,0,0,0,0,0
249,1.0,0.105249,0,0.823293,0.444812,0,0,0,0,0,1,0

# Filter method

In [5]:
df.to_csv('features.csv')

c:\users\enrmeao\pycharmprojects\coursing\venv\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

## Variance method
removing features that show the same value for the majority/all of the observations (constant/quasi-constant features)

In [16]:
def constant_feature_detect(data,threshold=0.98):
    """ detect features that show the same value for the 
    majority/all of the observations (constant/quasi-constant features)
    
    Parameters
    ----------
    data : pd.Dataframe
    threshold : threshold to identify the variable as constant
        
    Returns
    -------
    list of variables names
    """
    
    data_copy = data.copy(deep=True)
    quasi_constant_feature = []
    for feature in data_copy.columns:
        predominant = (data_copy[feature].value_counts() / np.float(
                      len(data_copy))).sort_values(ascending=False).values[0]
        if predominant >= threshold:
            quasi_constant_feature.append(feature)
    print(len(quasi_constant_feature),' variables are found to be almost constant')    
    return quasi_constant_feature

c:\users\enrmeao\pycharmprojects\coursing\venv\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [19]:
constant_feature_detect(data=df,threshold=0.9)

4  variables are found to be almost constant

['difficulty_Career Advancement',
 'difficulty_School of Autonomous Systems',
 'difficulty_School of Cloud Computing',
 'difficulty_School of Data Science']

In [20]:
def corr_feature_detect(data,threshold=0.8):
    """ detect highly-correlated features of a Dataframe
    Parameters
    ----------
    data : pd.Dataframe
    threshold : threshold to identify the variable correlated
        
    Returns
    -------
    pairs of correlated variables
    """
    
    corrmat = data.corr()
    corrmat = corrmat.abs().unstack() # absolute value of corr coef
    corrmat = corrmat.sort_values(ascending=False)
    corrmat = corrmat[corrmat >= threshold]
    corrmat = corrmat[corrmat < 1] # remove the digonal
    corrmat = pd.DataFrame(corrmat).reset_index()
    corrmat.columns = ['feature1', 'feature2', 'corr']
   
    grouped_feature_ls = []
    correlated_groups = []
    
    for feature in corrmat.feature1.unique():
        if feature not in grouped_feature_ls:
    
            # find all features correlated to a single feature
            correlated_block = corrmat[corrmat.feature1 == feature]
            grouped_feature_ls = grouped_feature_ls + list(
                correlated_block.feature2.unique()) + [feature]
    
            # append the block of features to the list
            correlated_groups.append(correlated_block)
    return correlated_groups

## Correlation method
remove features that are highly correlated with each other

In [21]:
corr = corr_feature_detect(data=df,threshold=0.9)
# print all the correlated feature groups!
for i in corr:
    print(i,'\n')